// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "forge-std/Script.sol";
import "../src/UnoGame.sol";

/**
 * @title DeployUnoGame
 * @notice Deploy script for UnoGame and all ZK verifier contracts
 * @dev Run with: forge script script/Deploy.s.sol:DeployUnoGame --rpc-url base_sepolia --broadcast --verify
 */
contract DeployUnoGame is Script {
    function run() external {
        uint256 deployerPrivateKey = vm.envUint("PRIVATE_KEY");
        require(deployerPrivateKey != 0, "PRIVATE_KEY not set");

        vm.startBroadcast(deployerPrivateKey);
        
        address deployer = vm.addr(deployerPrivateKey);
        console.log("Deploying with account:", deployer);

        // Deploy all verifier contracts using dynamic imports
        // Note: The verifier contracts are generated by Noir/BB and have the same interface
        
        console.log("\nDeploying ShuffleVerifier...");
        address shuffleVerifierAddr = deployCode("ShuffleVerifier.sol:HonkVerifier");
        console.log("ShuffleVerifier deployed to:", shuffleVerifierAddr);

        console.log("\nDeploying DealVerifier...");
        address dealVerifierAddr = deployCode("DealVerifier.sol:HonkVerifier");
        console.log("DealVerifier deployed to:", dealVerifierAddr);

        console.log("\nDeploying DrawVerifier...");
        address drawVerifierAddr = deployCode("DrawVerifier.sol:HonkVerifier");
        console.log("DrawVerifier deployed to:", drawVerifierAddr);

        console.log("\nDeploying PlayVerifier...");
        address playVerifierAddr = deployCode("PlayVerifier.sol:HonkVerifier");
        console.log("PlayVerifier deployed to:", playVerifierAddr);

        // Deploy UnoGame with verifier addresses
        console.log("\nDeploying UnoGame...");
        UnoGame unoGame = new UnoGame(
            shuffleVerifierAddr,
            dealVerifierAddr,
            drawVerifierAddr,
            playVerifierAddr
        );
        address unoGameAddr = address(unoGame);
        console.log("UnoGame deployed to:", unoGameAddr);

        vm.stopBroadcast();

        // Log deployment summary
        console.log("\n========================================");
        console.log("DEPLOYMENT SUMMARY");
        console.log("========================================");
        console.log("ShuffleVerifier:", shuffleVerifierAddr);
        console.log("DealVerifier:", dealVerifierAddr);
        console.log("DrawVerifier:", drawVerifierAddr);
        console.log("PlayVerifier:", playVerifierAddr);
        console.log("UnoGame:", unoGameAddr);
        console.log("========================================");
    }
}

/**
 * @title DeployUnoGameSimple  
 * @notice Deploy script for UnoGame without ZK verifiers (for testing)
 * @dev Uses mock verifier addresses
 */
contract DeployUnoGameSimple is Script {
    function run() external {
        uint256 deployerPrivateKey = vm.envUint("PRIVATE_KEY");
        require(deployerPrivateKey != 0, "PRIVATE_KEY not set");

        vm.startBroadcast(deployerPrivateKey);

        address deployer = vm.addr(deployerPrivateKey);
        console.log("Deploying with account:", deployer);

        // For simple deployment, we use placeholder addresses
        // These should be updated with real verifier addresses
        address mockVerifier = address(0x1);

        console.log("\nDeploying UnoGame with placeholder verifiers...");
        // Note: This will revert if verifiers are zero address
        // Using a test verifier pattern
        
        vm.stopBroadcast();
    }
}
